import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import axios from 'axios'
import Navbar from '@/components/Navbar'
import { ToastContainer, toast } from "react-toastify";
import Stable from '../components/Stable'


const inter = Inter({ subsets: ['latin'] })
const sleep = (ms: number | undefined) => new Promise((r) => setTimeout(r, ms));


export default function Home() {

  return (
    <>
      <Head>
        <title>Tattoo inspiration</title>
        <meta name="description" content="Generated by shadow" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="flex flex-col items-center justify-center"
        data-theme="autum"
      >
        <div className="hero min-h-screen bg-base-200">
          <div className="hero-content text-center">
            <div className="max-w-md">
              <h1 className="text-5xl font-bold">skin code</h1>
              <p className="py-6">
                Provident cupiditate voluptatem et in. Quaerat fugiat ut
                assumenda excepturi exercitationem quasi. In deleniti eaque aut
                repudiandae et a id nisi.
              </p>
              <button className="btn btn-primary">Get Started</button>
            </div>
          </div>
        </div>
    
      </div>
    </>
  );
}
